pref("extensions.firestatus.twitterEnabled", false);
pref("extensions.firestatus.twitterUpdatesEnabled", false);
pref("extensions.firestatus.twitterUsername", "");
pref("extensions.firestatus.twitterPassword", "");
pref("extensions.firestatus.twitterTimeout", 5);
pref("extensions.firestatus.lastTwitterId", 0);
pref("extensions.firestatus.lastTwitterTimestamp", "0");
pref("extensions.firestatus.friendfeedEnabled", false);
pref("extensions.firestatus.friendfeedUpdatesEnabled", false);
pref("extensions.firestatus.friendfeedUsername", "");
pref("extensions.firestatus.friendfeedPassword", "");
pref("extensions.firestatus.friendfeedTimeout", 4);
pref("extensions.firestatus.lastFriendfeedId", "");
pref("extensions.firestatus.facebookEnabled", false);
pref("extensions.firestatus.facebookUpdatesEnabled", false);
pref("extensions.firestatus.facebookTimeout", 6);
pref("extensions.firestatus.shortURLService", "tinyUrl");
// See http://kb.mozillazine.org/Localize_extension_descriptions
pref("extensions.firestatus@astithas.com.description", "chrome://firestatus/locale/firestatus.properties");
